version: '3.9'

services:
  prometheus:
    image: prom/prometheus:v2.39.1
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=90d'
      - '--storage.tsdb.retention.size=7GB'
      - '--web.external-url=/prometheus/'
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.prometheus.rule=Host(`${SERVER_IPV4}`) && PathPrefix(`/prometheus/`)"
        - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
  grafana:
    image: grafana/grafana:9.1.7
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./grafana.ini:/etc/grafana/grafana.ini
      - grafana-data:/var/lib/grafana
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.grafana.rule=Host(`${SERVER_IP}`) && PathPrefix(`/grafana/`)"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"
  speedtest:
    image: billimek/prometheus-speedtest-exporter:1.3.1
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9469:9469"

networks:
  traefik-public:
    external: true

volumes:
  prometheus-data:
  grafana-data:
