version: '3.9'

services:
  pihole:
    image: pihole/pihole:2022.09.4
    ports:
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: 'G9IMXfI6b7IPS7LZes54'
      DNSSEC: 'true'
      DHCP_ACTIVE: 'false'
      WEBTHEME: 'default-dark'
      FTLCONF_LOCAL_IPV4: ${SERVER_IPV4}
      FTLCONF_LOCAL_IPV6: ${SERVER_IPV6}
      PIHOLE_DNS_: 1.1.1.1;8.8.8.8;2001:4860:4860:0:0:0:0:8888;2606:4700:4700::1111
      TEMPERATUREUNIT: 'c'
      WEBUIBOXEDLAYOUT: 'boxed'
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - pihole-data:/etc/pihole
      - ./99-edns.conf:/etc/dnsmasq.d/99-edns.conf
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pihole.rule=Host(`${SERVER_IPV4}`) && PathPrefix(`/pihole/`)"
        - "traefik.http.services.pihole.loadbalancer.server.port=80"
        - "traefik.http.routers.pihole.middlewares=pihole"
        - "traefik.http.middlewares.pihole.replacepathregex.regex=^/pihole/(.*)"
        - "traefik.http.middlewares.pihole.replacepathregex.replacement=/admin/$$1"
        - "traefik.docker.network=traefik-public"

networks:
  traefik-public:
    external: true

volumes:
  pihole-data:
